### PR TITLE
Enable ci for master

### PR DESCRIPTION
**Pull request by LewisLiuPub**

### CODE REVIEW

**Comment by LewisLiuPub** [comment]
@huangjiafengx, please help review.

**Review by huangjiafengx — COMMENTED** [review]
Hi， could you change some issues for the reviewer.

**Comment by huangjiafengx** [comment]
The CI error for yolov5 model convert fail.

image

**Comment by huangjiafengx** [comment]
@LewisLiuPub 
All cases test pass.

**Pull request merged**
