### PR TITLE
Check ROI boundary in object/face detection

### PR DESCRIPTION
**Pull request by houk-intel**
This PR checks the ROI boundary in object/face detection. @LewisLiuPub @chaoli2 @RachelRen05, please have a review.

### CODE REVIEW

**Comment by LewisLiuPub** [comment]
@houk-intel thank you for your work. but it seems there are some conflicts after an earlier PR emerged. Please add a new patch to resolve these conflicts.

**Comment by LewisLiuPub** [comment]
@houk-intel change check ROI parameter in configuration file with the new name: "enable_roi_constraint", with comment: "set enable_roi_constraint to false if you don't want to make the inferred ROI (region of interest) constrained into the camera frame." or the like.

**Comment by houk-intel** [comment]
It is updated. And I added the enable_roi_constraint parameter in all the yaml files which include OBJECT or FACE detection inside.

**Comment by houk-intel** [comment]
@LewisLiuPub the confidence_threshold parameter is adjusted into each inference in yamls.

**Comment by LewisLiuPub** [comment]
@houk-intel you updated inputs from RealsenseCamera to StandardCamera in pipeline_object.yaml, it is unnecessary to make such change, otherwise, the related README file should also be modified. Please revert it.

**Comment by HoukChen** [comment]
It's restored now.

**Comment by LewisLiuPub** [comment]
Good for me. Merged.

**Pull request merged**
