### PR TITLE
Add pipeline manager

### PR DESCRIPTION
**Pull request by LewisLiuPub**

### CODE REVIEW

**Comment by LewisLiuPub** [comment]
@chaoli2 @houk-intel @RachelRen05 please have a review.

**Comment by houk-intel** [comment]
@LewisLiuPub Are there any changes of the commands to run the sample codes?

**Comment by houk-intel** [comment]
@LewisLiuPub Object configuration file (pipeline_object.yaml) seems haven't been modified, does the code support Object Detction now?

**Comment by LewisLiuPub** [comment]
> @LewisLiuPub Object configuration file (pipeline_object.yaml) seems haven't been modified, does the code support Object Detction now?

@houk-intel Yes, Object Detection is supposed to be supported by the new sample code. and you are right that the relative configuration file is not modified to align with the new code.

I am happy that @RachelRen05  will take some efforts for the modifying and validation tasks.

**Comment by LewisLiuPub** [comment]
> @LewisLiuPub Are there any changes of the commands to run the sample codes?

@houk-intel 
I am thinking it is not so good to keep sample programs with too many command-line arguments. In this version, I only keep one argument "-c" to provide configuration file path, while all other settings would be stored in and passed through the config file.

**Comment by chaoli2** [comment]
It's OK for me.

**Pull request merged**
