### PR TITLE
Object detection works now

### PR DESCRIPTION
**Pull request by houk-intel**
@LewisLiuPub @chaoli2  Modified object.yaml and add name check in pipeline-manager, please review.

### CODE REVIEW

**Comment by LewisLiuPub** [comment]
@houk-intel @RachelRen05 what difference between pipeline_object.yaml and pipeline_object_oss.yaml? do we need to keep 2 config files for object detection?

**Comment by RachelRen05** [comment]
@LewisLiuPub 
Yes, there are different model path between pipeline_object.yaml and pipeline_object_oss.yaml.
We also keep 2 config files for face detection.

**Comment by houk-intel** [comment]
@LewisLiuPub Yes, as @RachelRen05 said, the model file path is different between these two version. I suggest we put all .models/.labels/.bin files in a fixed path to avoid unnecessary confusion and repeated configuration files. Possible methods are
1.  Add a step in our README, let users copy the files into a suggested path.
2. Or just include the files into our projects.

**Comment by LewisLiuPub** [comment]
@RachelRen05 Suppose the installation scripts would meet houk's steps. Please help check.

**Comment by LewisLiuPub** [comment]
Per offline check, the PR will be merged and keep the current structure. For a long term, we'd check the necesity for the better resource management (model, label, engine, etc.).

**Pull request merged**
